sudo: false
language: python

matrix:
  include:
      - python: 3.8
      - python: 3.7
      - python: 3.6
      - python: pypy3

install:
  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then travis_retry pip install . -r requirements-ci.txt ; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy3" ]; then travis_retry pip install . pytest ; fi
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - ./tests/run_tests.py

  # Check wheather the imports were sorted correctly.
  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then isort -c -rc ptpython tests setup.py examples ; fi

  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then black --check ptpython setup.py examples ; fi
