sudo: false
language: python

matrix:
  include:
      - python: 3.8
      - python: 3.7
      - python: 3.6
      - python: pypy3

install:
  - travis_retry pip install . -r requirements-ci.txt
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - ./tests/run_tests.py

  # Check wheather the imports were sorted correctly.
  - isort -c -rc ptpython tests setup.py examples

  - black --check ptpython setup.py examples
